[window]
opacity = 1.0
padding = { x = 22, y = 22 } # Замена window_margin_width 21.75
decorations = "full"

# Шрифты
[font]
size = 11.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

# Курсор
[cursor]
style = { shape = "Beam" }

# Оболочка (Fish)
[terminal.shell]
program = "fish"

[general]
import = ["~/.config/alacritty/alacritty-colors.toml"]

