# Основные цвета
background            #0f1511
foreground            #dfe4dd
cursor                #94d5a9
selection_background  #374b3d
selection_foreground  #d1e8d5

# Цвета 0-7 (Normal)
color0  #0f1511
color1  #ffb4ab
color2  #94d5a9
color3  #b5ccba
color4  #a3cddb
color5  #0c5130
color6  #374b3d
color7  #c0c9c0

# Цвета 8-15 (Bright)
color8  #8a938b
color9  #93000a
color10 #94d5a9
color11 #b5ccba
color12 #a3cddb
color13 #2b6a46
color14 #214c58
color15 #dfe4dd
